import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { getNews, saveStored } from '../../../../data/content'

export default function NewsForm() {
  const { id } = useParams(); const navigate = useNavigate(); const existing = id ? getNews().find(x => x.id === Number(id)) : null
  const [form, setForm] = useState(existing || { title:'', category:'MINISTRY NEWS', date:'', image:'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1000&q=80', excerpt:'', content:'' })
  const update = (e) => setForm({...form, [e.target.name]: e.target.value})
  const submit = (e) => { e.preventDefault(); const all = getNews(); const item = {...form, id: existing?.id || Date.now()}; saveStored('mw_news', existing ? all.map(x => x.id === existing.id ? item : x) : [item, ...all]); navigate('/admin/news') }
  return <><div className="admin-page-heading"><div><div className="eyebrow">CONTENT MANAGEMENT</div><h2>{existing ? 'Edit News' : 'Create News'}</h2><p>Prepare a professional ministry news article for the public website.</p></div><Link to="/admin/news" className="btn btn-light rounded-pill px-4">Back to News</Link></div>
    <form onSubmit={submit} className="admin-card p-4"><div className="row g-4"><div className="col-lg-8"><label className="form-label">Headline</label><input required name="title" value={form.title} onChange={update} className="form-control mb-3" placeholder="Enter news headline"/><label className="form-label">Article content</label><textarea required name="content" value={form.content} onChange={update} className="form-control" rows="11" placeholder="Write the full news article..."/><small className="text-muted">Use blank lines to separate paragraphs.</small></div><div className="col-lg-4"><label className="form-label">Category</label><select name="category" value={form.category} onChange={update} className="form-select mb-3"><option>MINISTRY NEWS</option><option>PROJECTS</option><option>POLICY</option><option>ANNOUNCEMENT</option></select><label className="form-label">Publication date</label><input required name="date" value={form.date} onChange={update} className="form-control mb-3" placeholder="12 AUG 2026"/><label className="form-label">Featured image URL</label><input name="image" value={form.image} onChange={update} className="form-control mb-3"/><label className="form-label">Short excerpt</label><textarea required name="excerpt" value={form.excerpt} onChange={update} className="form-control" rows="5" placeholder="Short summary shown on news cards..."/></div></div><div className="border-top mt-4 pt-4 d-flex justify-content-end gap-2"><Link to="/admin/news" className="btn btn-light rounded-pill px-4">Cancel</Link><button className="btn btn-primary rounded-pill px-4"><i className="bi bi-check2-circle me-2"/>{existing ? 'Update News' : 'Publish News'}</button></div></form></>
}
